CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(35) NOT NULL,
  "email" varchar(50) NOT NULL,
  "password" int NOT NULL,
  "edad" int NOT NULL,
  "roles_id" smallint
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) NOT NULL,
  "description" varchar(500),
  "level" int NOT NULL,
  "teacher" varchar(25) NOT NULL,
  "courses_id" int NOT NULL
);

CREATE TABLE "courses_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) NOT NULL,
  "url" varchar(100),
  "courses_id" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL,
  "courses_id" int
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id") REFERENCES "categories" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("roles_id") REFERENCES "roles" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");
